# Server Configuration
server.port=8083
spring.application.name=payment-service

# DB_URL_PAYMENT=jdbc:mysql://localhost:3306/payment;DB_USERNAME_PAYMENT=root;DB_PASSWORD_PAYMENT=admin

# MySQL Configuration
spring.datasource.url=${DB_URL_PAYMENT:jdbc:mysql://localhost:3306/payment}
spring.datasource.username=${DB_USERNAME_PAYMENT:root}
spring.datasource.password=${DB_PASSWORD_PAYMENT:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# External Services URLs
service.booking.url=${SERVICE_BOOKING_URL:http://localhost:8082/api/bookings}
service.event.url=${SERVICE_EVENT_URL:http://localhost:8081/api/events}
