# Application Configuration
spring.application.name=booking-service
server.port=8082

# DB_URL_BOOKING=jdbc:mysql://localhost:3306/booking;DB_USERNAME_BOOKING=root;DB_PASSWORD_BOOKING=admin

# MySQL Database Configuration
spring.datasource.url=${DB_URL_BOOKING:jdbc:mysql://localhost:3306/booking}
spring.datasource.username=${DB_USERNAME_BOOKING:root}
spring.datasource.password=${DB_PASSWORD_BOOKING:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# External Services URLs
service.user.url=${SERVICE_USER_URL:http://localhost:8080/api/users}
service.event.url=${SERVICE_EVENT_URL:http://localhost:8081/api/events}
